name: gym_fitness_app
description: "A professional Gym & Fitness Flutter application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  pedometer: ^4.0.0
  permission_handler: ^11.0.0
  flutter:
    sdk: flutter

  # Core
  flutter_riverpod: ^2.6.1
  go_router: ^14.0.0

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_database: ^11.0.0 # Using Realtime Database

  # Utilities/UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  uuid: ^4.5.2
  intl: ^0.20.2
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true